### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by jadudm** [IMLS/estimating-wifi#1]
**As a library employee with administrative access on a circulation machine, I want to be able to install the `session-counter` and confirm it is working.**

### Acceptance Criteria

1. I receive an email with my API key, so that I can complete the installation.
2. I am provided a link to download the installer, so that I can do the install.
3. I have documentation I can refer to during the installation.
4. If the installer fails, I have clear reasons presented and am shown/told where to go/what to do in the event of installer failure, so that I feel confident about the process even if something "goes wrong."
5. I have external confirmation (e.g. a link) that I can visit to confirm that my installation worked and the "circdesk sensor" is working correctly. 

### Resources:

* Mockups: 
* Testing URL: 
* Staging URL: 

### Notes

[Some complementary notes if necessary:]

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

**Comment by wesley-dean-gsa** [comment]
recommend against sending API keys over email in order to maintain compliance with relevant FIPS / NIST controls and FISMA legislation.

**Comment by jadudm** [comment]
What are alternative dissemination mechanisms? Post?

**Comment by jadudm** [comment]
So, per further conversation, we wonder if NSIS might allow us to build an installer on Linux. This would allow us to change the story, so an installer contains the appropriate keys, and a librarian could directly download or be given the installer (perhaps on a USB stick, mailed to their library), thus simplifying the user experience and addressing some security concerns.

**Comment by wesley-dean-gsa** [comment]
I created #11 to break out the API key topic from this issue.

**Comment by meenubhooshanan** [comment]
Stale ticket
