### ISSUE TITLE
Reporting UI

### ISSUE THREAD

**Issue by sknep** [IMLS/estimating-wifi#12]
(WIP) 

As a user, in order to review wifi usage for the libraries I'm responsible for, I want to see the sensor-collected data in a useful way.

### Acceptance Criteria

1. The user can choose one or more dashboards to view, which display information at a sensor or library (TBD) level.

### Notes
This is probably more of an Epic but everyone else has stories and I want to write down something :)

#### How do we help admins infer different kinds of wifi usage?
Short, medium, long sessions divisions?
Would such divisions be configurable between sensors/libraries or consistent across all sensors?

#### How do we help admins report changes in usage over time?
Hourly, Daily, Weekly, Monthly, Yearly reporting
Comparing week-to-week, day-to-day, this time last year
Seasonality & special programming (calendar?)
Wifi usage during library open hours vs closed (configurable?)

#### How do we help admins report changes in usage over time?
Hourly, Daily, Weekly, Monthly, Yearly reporting
Comparing week-to-week, day-to-day, this time last year
Seasonality & special programming (calendar?)
Wifi usage during library open hours vs closed (configurable?)

#### Other
export data to table/csv
door count information?

**Comment by jreme100** [comment]
Ticket closed - super broad ticket. Probably all of the front end stuff will contribute to this.
