### ISSUE TITLE
Add basic security scanning

### ISSUE THREAD

**Issue by wesley-dean-gsa** [IMLS/estimating-wifi#15]
As a security engineer, so that issues may be identified quickly and without manual intervention, I would like to have automated tooling that scans our code, containers, etc. for common security concerns, dependency updates, etc..

# Acceptance Criteria

1. automated processes run against our code base either on periodic or event-driven basis
2. findings are tracked and communicated

## Optional Criteria

1. SARIF support

# Resources:

* semgrep.dev
* snyk.io
* codeql.github.com
* dependabot.com

### Notes

As with #14 , these are common processes used by other GSA / 10x projects and are run in a CI/CD context

**Comment by wesley-dean-gsa** [comment]
for deployed applications with a web interface, consider [OWASP ZAP](https://www.zaproxy.org/)

**Comment by wesley-dean-gsa** [comment]
#14 added MegaLinter (PR #27) that included Devskim, Dustilock, gitleaks, secretlint, Semgrep, Trivy, and others.  Recommend continuing efforts by incorporating CodeQL, Dependabot, and Snyk.

**Comment by anagradova** [comment]
Will look at incorporating security tools into the MegaLinter or other build process.

**Comment by wesley-dean-gsa** [comment]
@anagradova 
Examples from 10x projects:
* Snyk: https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/snyk.yml
* CodeQL: https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/codeql-analysis.yml

**Comment by wesley-dean-gsa** [comment]
Dependabot: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

**Comment by anagradova** [comment]
Thank you! I will grab these tasks, the ADR for #15 was pushed and merged. Please take a look, when you have a chance.
