### ISSUE TITLE
As a library manager, I want to access h/d/w/m/y summaries of a given library's wifi presences for reporting and resource allocation purposes.

### ISSUE THREAD

**Issue by meenubhooshanan** [IMLS/estimating-wifi#33]
**As a library manager, I want to access h/d/w/m/y summaries of a given library's wifi presences for reporting and resource allocation purposes.**

### Acceptance Criteria

1. Mock up / lo-fi prototype initial examples of h/d summary.
2. Pilot initial visualization using lo-code/prototyping tools (Google Collab / Sheets)

### Depends on 

- #34 
- #20 

[

]

### Resources

* Mockups:
* Testing URL:
* Staging URL:

### Notes

[Some complementary notes if necessary:]

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

**Comment by sknep** [comment]
did we intentionally choose library as opposed to sensor here? to me, this implies sensor grouping to a single library.

**Comment by jreme100** [comment]
I guess that's an interesting question - I would think the "user" (which is also vague) wouldn't care which sensor the data was coming off of if they had five within the same library? So in that sense maybe the csv and/or visualization would be pulled from the IMLS id (library)?

**Comment by jreme100** [comment]
I'm going to close this "not planned" because it is represented both in the currently existing epics and we are doing separate stories for hour, day, etc.
